### PR TITLE
Design doc template

### PR DESCRIPTION
**Pull request by tranma**
This is one way of specifying the design doc.

I don't have an example ready at hand, but this is the outline of what I remember.

WIP until we agree on a standard

### CODE REVIEW

**Comment by fractalcat** [comment]
How much detail would these design docs include? What would be a typical length?

**Comment by tranma** [comment]
enough detail that someone who has had no contact with the project could read and pick it up. Length depends on the complexity of the project.

**Comment by fractalcat** [comment]
Sounds arduous - maybe useful but lots of effort. Who writes them, given we don't have any PhDs yet? What kind of errors does the process usually catch? I'd be happy to try it at least for one sprint.

**Comment by tranma** [comment]
The engineer-in-charge, aka person who write most of the implementation.
They aren't meant to catch anything, but to document the details you manage to find out pre-implementation, so that you don't end up forgetting them.

**Comment by christian-marie** [comment]
OK Let's give this a go. I don't think it's over the top at all if it doubles as an overview of the system.

**Pull request merged**
